const homeData=[
{"sourceUuid":"np_dH49e8QQ2HH_-WkkK2l7yxPYcaGvMyErP3nJFNlwoa1VJQ","title":"官途：权色撩人","cover":"https://easyreadfs.nosdn.127.net/nfb.367f3edaa4ff43009f5528734428d969.jpg","author":"丁公子","totalCount":"414.2万","serial":true,"category":"官场职场","description":"智谋如妖，仕途之路争斗不断，一路横推对手，平步青云。青云之路，美人环绕，一路开到荼靡。不断登临权力之巅，财富、美色纷至沓来，各色人物粉墨登场。人生如戏，戏如人生。欲知官妖如何决胜千里，请看官场草根的逆袭之路。"},
{"sourceUuid":"np_IilrLMlB3n-s-Dp0K2ovmUiLI679OikmbS2YE49z_a1VJQ","title":"官路","cover":"https://easyreadfs.nosdn.127.net/nfb.6f2095f2bae84da5855888d7875e35ce.jpg","author":"钓人的鱼","totalCount":"582.8万","serial":true,"category":"官场职场","description":"为官者，踏出一步，就是一个脚印，对了，那是份内之事，错了，前面就是万丈深渊；本书的姊妹篇，也可以说是《官梯》的续集，《村长的妖孽人生》正在网易云阅读火热连载，《官梯》里没有交代的事这里都会交代清楚，敬请观赏。http://yuedu.163.com/source/1b7140a1bb4e4ec3bcbb08e5e0093cee_4另有完本作品《国色天香》也在网易云阅读。"},
{"sourceUuid":"np_c3xtL8lH3XCs_WshKz8kyRPfJK-tP3Ioai-cF49-qftVJQ","title":"一号秘书：陆一伟传奇","cover":"https://easyreadfs.nosdn.127.net/novel_c2408b035eca4fa199ff1f633bd0d756.jpeg","author":"万路之遥","totalCount":"367.3万","serial":true,"category":"官场职场","description":"陆一伟，一个铁骨铮铮，有血有肉的七尺男儿，他心系群众，种植果园不忘百姓，舍弃己利无偿捐赠；他侠骨仁心，兄弟落难两肋插刀，重情重义肝胆相照；他饱尝妻离子散、亲友远离的人间冷暖，面对爱情、友情、亲情的抉择，却另辟蹊径，重新打开了通往成功的大门。这是一部充满正能量的写实小说，一部小人物百折不挠、不卑不亢的心路历程，用打脱牙和血吞的毅力书写着平凡的人生。此文谨献给奋斗路上的你我，一起见证一段不一样的奋斗历程……qq:406002220，欢迎大家一起交流探讨。"},
{"sourceUuid":"np_KHw4K85J3Xas_zhwKzl5yBCNJquoPHQrOHzKE4p3rKlVJQ","title":"兵王都市传奇","cover":"https://easyreadfs.nosdn.127.net/nfb.f9bc2c574e6948d3bb0a60d11c5128c3.jpg","author":"我自对天笑","totalCount":"683.6万","serial":true,"category":"都市生活","description":"雇佣兵王陈扬回归都市，只为保护战友的女神妹妹。繁华都市里，陈扬如鱼得水，逍遥自在。且看一代兵王如何用铁拳和智慧打下一片商业帝国……欲了解四帝更多故事，请微信公众号搜索天道盟。"},
{"sourceUuid":"np_cCk5fsVGinSg_Th3Kz54yxDdfvzyayMobS6bSNd_qfJVJQ","title":"桃色官路：情陷女领导","cover":"https://easyreadfs.nosdn.127.net/nfb.4d38cd27236c4c2fb6d51f15ae49f964.jpg","author":"风语","totalCount":"325.8万","serial":true,"category":"官场职场","description":"国税局小科员凌正道，因不够圆滑，在工作中被一直打压。一天醉酒后，他无意间撞破了副局长唐立君与县委书记夫人赵丽然的秘密，被唐局长从征税科调到办公室工作……自此，他开始了真正的仕途之路，各色各样的美女也接踵而来，令人眼花缭乱！"},
{"sourceUuid":"np_IyxjJc9F2X-srjl1K2t7zBCMJP3-MyN7Y3zLQdd1q_5VJQ","title":"夜行者：平妖二十年","cover":"https://easyreadfs.nosdn.127.net/novel_0114ebfd5fa345c587183ba972dd16ce.jpeg","author":"南无袈裟理科佛","totalCount":"153.4万","serial":true,"category":"悬疑探险","description":"“苗疆三部曲”作者南无袈裟理科佛新作。\r\n“人之假造为妖，物之性灵为精，人魂不散为鬼。天地乖气，忽有非常为怪，神灵不正为邪，人心癫迷为魔，偏向异端为外道。”\r\n南漂青年侯漠，在98年的一次变故之中，发现自己身上藏着夜行者的血脉，而且还是十分特殊的“灵明石猴”，这是一种遭受上天诅咒的血脉，有着活不过三十的基因缺陷，为了活下去，他不得不从踏入那个前所未闻的江湖岁月，拼命挣扎。\r\n七大妖穴、游侠联盟、民国十大高手与清朝遗老的恩怨、诡异纷繁的民间传说和让人为之心悸的乡野秘闻，城市之中的迷藏，还有最骇人听闻的黄泉引，你有所耳闻却从未了解过的真相，所有一切，尽在《夜行者：平妖二十年》！\r\n"},
{"sourceUuid":"np_cCZtJcxAi3aqrjN3K297zkjYf6-pPCl8Y3_IQt93-_hVJQ","title":"美女总裁的特种保镖","cover":"https://easyreadfs.nosdn.127.net/nfb.5c3d364658b546849bc1a9e13b13a10c.jpg","author":"风流小二","totalCount":"394.2万","serial":true,"category":"都市生活","description":"【年度最畅销的都市大作】叶凌天，神秘部队退伍军人，为了给妹妹凑集五十万的治疗费用不得不给三元集团的千金小姐李雨欣当贴身保镖。且看经历过太多生死的铮铮硬汉叶凌天如何在这个繁华都市里走出属于自己的一条不平凡的路来。"},
{"sourceUuid":"np_Jyw6fMUT3yGp-DIoK29-yUmKf_z4aSd9ayqeQ9ty_PJVJQ","title":"都市护花神医","cover":"https://easyreadfs.nosdn.127.net/nfb.df0d12128185487e916adb97fa9c08c8.jpg","author":"就爱吃海椒","totalCount":"334.1万","serial":true,"category":"都市生活","description":"上班第一天就和23岁的霸道女总裁发生了关系，她发誓要让我跪下唱征服，不择手段要把我拴在身边。为了挽回一个男人的尊严，我拼了！"},
{"sourceUuid":"np_c3sEJM1G3yWp-2lwemwlyUTaf6H_MnQtbnnOF493rqg7JXoEKQ","title":"纵横官场之权色无边","cover":"https://easyreadfs.nosdn.127.net/nfb.ff7d680f330e4c5aa1b969c09c99a6a6.jpg","author":"山间老寺","totalCount":"792.8万","serial":true,"category":"官场职场","description":"李睿在单位里被美女上司无情欺压，家里面老婆红杏出墙，陷入了人生最低谷。在一次防汛检查时，他跟上司袁晶晶闹翻，事后才知她是市里某领导的儿媳。山洪暴发，李睿凑巧救了某位贵人，自此成为了市里的大红人……"},
{"sourceUuid":"np_JnppLZkV23Cv-T4mKzktnkjed6n-OyUobSXFF94mqalVJQ","title":"国色天香（全文）","cover":"https://easyreadfs.nosdn.127.net/novel_aa5aa1fc398846f29b786e24dd78931f.jpeg","author":"钓人的鱼","totalCount":"390.6万","serial":false,"category":"都市生活","description":"莫小鱼，一个老老实实的黑车司机，做梦都想不到因为一单黑车生意将自己的人生完全改变，一个套接着一个套，一个局接着一个局，美女设局也就罢了，老子忍了，妈的，你一个糟老头子也来设局害我……\n作者还有两本书《官梯》，《村长的妖孽人生》也非常的精彩，大家可以看一下，保证物有所值。都在网易云阅读。\n"},
{"sourceUuid":"np_IClvK8UQ3Xf7-TInK297xRPbfvquPSEvaS_JFdt-oKhVJQ","title":"官途沉浮","cover":"https://easyreadfs.nosdn.127.net/nfb.5b45e0e856414982aacc827e5b057732.jpg","author":"草蛇灰线","totalCount":"756.9万","serial":false,"category":"官场职场","description":"在基层混迹多年毫无晋升希望的梁健，得到区委女书记的欣赏，从乡镇干部一路跋涉攀升，在权和情的漩涡中，渐渐领会到权道、情道和人道！本文开头有点闷骚，看下去会回味无穷！何以解忧，唯有更新！"},
{"sourceUuid":"np_ISc6L58TjXShrT0lKzosnBDacKDzaXMrbyyYSYwkr6lVJQ","title":"官场神秘人","cover":"https://easyreadfs.nosdn.127.net/nfb.6187e7824ff54d71bfe55cb71136db67.jpg","author":"阿诸","totalCount":"221万","serial":true,"category":"官场职场","description":"县府大秘薛家良，因县长受贿案遭到无情打压，本可以顺利接班的他，与主任宝座失之交臂。仕途不顺，一切皆不顺。先是被带走调查，后又经历了降职使用、女友背离、母亲去世等一系列打击，正当他的人生处于最低谷时，一个神秘人物出现了，从此，他的命运出现转机且迅速触底反弹，不可思议地成为炙手可热的人物……（姊妹篇《权力之巅》，已经完结，点击作者“阿诸”即可。）"},
{"sourceUuid":"np_c3sEfMpEi3Cp-GkiKmN8yUXcI6D6aCIqaXieQNZyrfg7d3kEKQ","title":"医道圣手在都市","cover":"https://easyreadfs.nosdn.127.net/nfb.814890e8230d4ddd813b536793dd67a1.jpg","author":"一念","totalCount":"861.6万","serial":true,"category":"都市生活","description":"实习医生叶皓轩，意外的得到一本古书上的玄术与医道传承，自此开始了不一样的人生，他银针渡人，术法渡鬼，成就济世仁心，医道问卜 、风水勘舆无所不精。且看主角如何弘扬华夏传统文化。\r\n\r\n"},
{"sourceUuid":"np_c3sEKcxJ1nep-DpyeTkvyRLef_upMiB-OHmcF910_K85JCkEKQ","title":"官谋高手","cover":"https://easyreadfs.nosdn.127.net/454objeGbIORuBcLyzg3mA==/8796093023608928407","author":"梦入洪荒","totalCount":"760.8万","serial":true,"category":"官场职场","description":"官之途，民为本，为官一任，造福一方！军人出身的柳擎宇，毅然转业进入官场，成为乡镇镇长。然而上任当天却被完全架空，甚至被晾在办公室无人理睬！\r\n且看脾气火爆，办事雷厉风行的他，如何运用机智的头脑和层出不穷的手段。\r\n几十次微妙的官位升迁，数千场激烈的明争暗斗争。\r\n翻手间覆灭种种阴谋，步步高升！\r\n历经波折，踏上权力的巅峰！\r\n\r\n网易云阅读    小说官方粉丝群 ：98519115  \r\n作品交流，看书分享，书迷线上线下活动。\r\n并且提供每日、每周免费正版书籍福利，书籍阅读讨论尽在此地。"},
{"sourceUuid":"np_cyxuKMVD13f8_T8gKz4vzUjbdqivP3AsbyvOE9x3-6hVJQ","title":"侯沧海商路笔记","cover":"https://easyreadfs.nosdn.127.net/novel_f69da1cc923e4ab9ae0bec6819eadf3b.jpeg","author":"小桥老树","totalCount":"143.3万","serial":true,"category":"官场职场","description":"山南省首富侯沧海传奇创业故事。《奋斗者：侯沧海商路笔记》全面上市！这是一部民企教父的商路传奇奋斗史，也是每一个人的命运打拼史，唯有奋斗者才能主宰自己的命运！潜心五年突破之作，翻开本书，尽揽中国20年跌宕起伏商业风云！购买请戳：http://product.dangdang.com/25154996.html"},
{"sourceUuid":"np_c3sEKMhGiCb7_Dgke2p7yUjZJPivPSkmOSzJQtp1qKgyJykEKQ","title":"超凡兵王","cover":"https://easyreadfs.nosdn.127.net/nfb.6274bf51aa2f440ba162e055c5e2bd17.jpg","author":"暗夜行走","totalCount":"907.9万","serial":true,"category":"都市生活","description":"一代军刀重归都市，凭着一双铁拳再战天下，一声怒喝，世界皆震，且看军中王者洛天如何携美俯众生，霸气凌天下。"},
{"sourceUuid":"np_KSdtL8tEj3P_r28kK2wpmBOPd6_7ayMvbC6bQ9xx_65VJQ","title":"女神的贴身近卫","cover":"https://easyreadfs.nosdn.127.net/nfb.8f6f538548ea43f2814df6e8d15ff018.jpg","author":"我自对天笑","totalCount":"522万","serial":false,"category":"官场职场","description":"特种兵王陈凌在得知与妹妹相依为命的爷爷去世后，他毅然退役，选择回到东江照顾妹妹。都市繁华里，他超然的风采，惹得精英女白领，小萝莉，美丽御姐均对他芳心暗许。面对权力的诱惑，陈凌坚守心中的忠义，而当有一天，他被忠义所害····从此，抛掉压抑的良心，露出狰狞的本性。加入绝色尘姐的杀手组织，用最快的刀，杀最狠的人。纵横国内，驰骋国际大舞台，拉起一曲轰轰烈烈的……"},
{"sourceUuid":"np_cChiJZxC3XP6-ml1K28pyBOLIvuqM3d8aSvPENdwqv5VJQ","title":"罪恶调查局","cover":"https://easyreadfs.nosdn.127.net/nfb.3a691be492764451b51780bc86b2a358.jpg","author":"骁骑校","totalCount":"102.7万","serial":true,"category":"都市生活","description":"一个初出校园的大好青年，一个古灵精怪的混血少女，再加上一个肾上腺切除，混吃等死的老记者，开着一辆五菱宏光，这就是罪恶调查局目前的全部阵容。\r\n"},
{"sourceUuid":"np_ci5sL8RG3HX4_TgnKz58y0jfJaCvP3coayWeRYhz-q1VJQ","title":"和美女领导同居的日子","cover":"https://easyreadfs.nosdn.127.net/_a1-n1o1Nm3CD-Ryon0wZQ==/8796093023608073723","author":"可是你不快乐_我也是","totalCount":"393万","serial":true,"category":"都市生活","description":"我叫刘芒，但她......哦不，她们，却喜欢叫我流氓。如果你执意叫我流氓，我不介意流给你看。傲娇女上司，凶残女警花，温柔女房东，泼辣女明星。来吧来吧，看我如何从屌丝过街，变得君临天下！"},
{"sourceUuid":"np_IyY9fMRH1378-D1zK20knxDXIvz4a3d8OC3ERY0jqP1VJQ","title":"我在女监的管教生活","cover":"https://easyreadfs.nosdn.127.net/nfb.c8bc4e3f4fa04948b56bf777c44d6bb2.jpg","author":"总经理秘书","totalCount":"789.4万","serial":true,"category":"官场职场","description":"在面试时，发现主考官竟是和自己有过关系的年轻女监狱长，走了好运的张帆进入女子监狱，成了这间监狱里面的唯一一个男管教。在监狱里，一大波女囚犯和犯罪阴谋接踵而至，为了各自目的，她们不惜付出任何代价靠近张帆，看张帆如何用智慧将女罪犯们全部绳之以法。一个小人物用智慧和勇气对付一个个犯罪团伙的正能量作品。"}
]
export default homeData;